/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.Dimension;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author esteb
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ventanaprincipal = new javax.swing.JDesktopPane();
        jButton1 = new javax.swing.JButton();
        menubarprincipal = new javax.swing.JMenuBar();
        administracionmnu = new javax.swing.JMenu();
        productomnu = new javax.swing.JMenuItem();
        categoriamnu = new javax.swing.JMenuItem();
        menumnu = new javax.swing.JMenuItem();
        monederomnu = new javax.swing.JMenuItem();
        promocionesmnu = new javax.swing.JMenuItem();
        gestionventasmnu = new javax.swing.JMenu();
        ventasmnu = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Ventanaprincipal.setBackground(new java.awt.Color(255, 255, 255));
        Ventanaprincipal.setForeground(new java.awt.Color(255, 255, 255));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-salida-50.png"))); // NOI18N
        jButton1.setText("Cerrar Sesion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Ventanaprincipal.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout VentanaprincipalLayout = new javax.swing.GroupLayout(Ventanaprincipal);
        Ventanaprincipal.setLayout(VentanaprincipalLayout);
        VentanaprincipalLayout.setHorizontalGroup(
            VentanaprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VentanaprincipalLayout.createSequentialGroup()
                .addGap(0, 249, Short.MAX_VALUE)
                .addComponent(jButton1))
        );
        VentanaprincipalLayout.setVerticalGroup(
            VentanaprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaprincipalLayout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(0, 159, Short.MAX_VALUE))
        );

        getContentPane().add(Ventanaprincipal, java.awt.BorderLayout.CENTER);

        administracionmnu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-herramientas-del-administrador-80.png"))); // NOI18N
        administracionmnu.setText("Administracion");

        productomnu.setText("Gestionar producto");
        productomnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productomnuActionPerformed(evt);
            }
        });
        administracionmnu.add(productomnu);

        categoriamnu.setText("Gestionar Categoria");
        categoriamnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriamnuActionPerformed(evt);
            }
        });
        administracionmnu.add(categoriamnu);

        menumnu.setText("Gestionar menu ");
        menumnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menumnuActionPerformed(evt);
            }
        });
        administracionmnu.add(menumnu);

        monederomnu.setText("Gestionar monedero");
        monederomnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monederomnuActionPerformed(evt);
            }
        });
        administracionmnu.add(monederomnu);

        promocionesmnu.setText("Gestionar Promociones");
        promocionesmnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promocionesmnuActionPerformed(evt);
            }
        });
        administracionmnu.add(promocionesmnu);

        menubarprincipal.add(administracionmnu);

        gestionventasmnu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-cuenta-80.png"))); // NOI18N
        gestionventasmnu.setText("Gestion de Ventas");

        ventasmnu.setText("Gestionar Ventas");
        ventasmnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventasmnuActionPerformed(evt);
            }
        });
        gestionventasmnu.add(ventasmnu);

        menubarprincipal.add(gestionventasmnu);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-salida-80.png"))); // NOI18N
        jMenu3.setText("Salir");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItem6.setText("Salir");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        menubarprincipal.add(jMenu3);

        setJMenuBar(menubarprincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
      
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
 System.exit(0);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void productomnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productomnuActionPerformed
        VentanaProducto vp=new VentanaProducto();
        Centrarventana(vp);
        
    }//GEN-LAST:event_productomnuActionPerformed

    private void categoriamnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriamnuActionPerformed
        VentanaCategoria vc=new VentanaCategoria();
        Centrarventana(vc);
    }//GEN-LAST:event_categoriamnuActionPerformed

    private void menumnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menumnuActionPerformed
        VentanaMenu vmnu=new VentanaMenu();
        Centrarventana(vmnu);
    }//GEN-LAST:event_menumnuActionPerformed

    private void monederomnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monederomnuActionPerformed
        VentanaMonedero vm=new VentanaMonedero();
        Centrarventana(vm);
    }//GEN-LAST:event_monederomnuActionPerformed

    private void promocionesmnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_promocionesmnuActionPerformed
       VentanaPromociones vprom=new VentanaPromociones();
        Centrarventana(vprom);
    }//GEN-LAST:event_promocionesmnuActionPerformed

    private void ventasmnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventasmnuActionPerformed
        Ventanacajero vc=new Ventanacajero();
        Centrarventana(vc);
    }//GEN-LAST:event_ventasmnuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Login lg =new Login();
        lg.setVisible(true);
        this.dispose();
        JOptionPane.showMessageDialog(null, "Sesion ccerra ecitosamente");
    }//GEN-LAST:event_jButton1ActionPerformed

    void Centrarventana(JInternalFrame frame){
        Ventanaprincipal.add(frame);
        Dimension dimension=Ventanaprincipal.getSize();
        Dimension fr=frame.getSize();
        frame.setLocation((dimension.width-fr.height)/2, (dimension.height-fr.width)/2);
        frame.show();
    }
            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Ventanaprincipal;
    public static javax.swing.JMenu administracionmnu;
    private javax.swing.JMenuItem categoriamnu;
    private javax.swing.JMenu gestionventasmnu;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem6;
    public static javax.swing.JMenuBar menubarprincipal;
    private javax.swing.JMenuItem menumnu;
    private javax.swing.JMenuItem monederomnu;
    private javax.swing.JMenuItem productomnu;
    private javax.swing.JMenuItem promocionesmnu;
    private javax.swing.JMenuItem ventasmnu;
    // End of variables declaration//GEN-END:variables
}
