/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controlador.CategoriaControlador;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author esteb
 */
public class VentanaCategoria extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaCategoria
     */
    public VentanaCategoria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtdescripcion = new javax.swing.JTextField();
        añadircatbtn = new javax.swing.JButton();
        eliminarcatbtn = new javax.swing.JButton();
        modificarcatbtn = new javax.swing.JButton();
        buscarcatbtn = new javax.swing.JButton();
        mostrartodoscatbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla3 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtidmenu = new javax.swing.JTextField();
        txtidpromocion = new javax.swing.JTextField();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gestionar Categoria");

        jLabel1.setText("Descripcion");

        jLabel2.setText("Id Categoria");

        añadircatbtn.setBackground(new java.awt.Color(255, 0, 0));
        añadircatbtn.setText("Añadir Categoria");
        añadircatbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadircatbtnActionPerformed(evt);
            }
        });

        eliminarcatbtn.setBackground(new java.awt.Color(255, 0, 0));
        eliminarcatbtn.setText("Eliminar Categoria");
        eliminarcatbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarcatbtnActionPerformed(evt);
            }
        });

        modificarcatbtn.setBackground(new java.awt.Color(255, 0, 0));
        modificarcatbtn.setText("Modificar Categoria");
        modificarcatbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarcatbtnActionPerformed(evt);
            }
        });

        buscarcatbtn.setBackground(new java.awt.Color(255, 0, 0));
        buscarcatbtn.setText("Buscar Categoria");
        buscarcatbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarcatbtnActionPerformed(evt);
            }
        });

        mostrartodoscatbtn.setBackground(new java.awt.Color(255, 0, 0));
        mostrartodoscatbtn.setText("Mostar todos");
        mostrartodoscatbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrartodoscatbtnActionPerformed(evt);
            }
        });

        tabla3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla3);

        jLabel3.setText("id menu");

        jLabel4.setText("id promocion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(modificarcatbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(añadircatbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(eliminarcatbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buscarcatbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(46, 46, 46))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(80, 80, 80)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3))
                                    .addGap(40, 40, 40)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtdescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                .addComponent(txtidmenu)
                                .addComponent(txtidpromocion)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(57, 57, 57)
                            .addComponent(jLabel2)
                            .addGap(37, 37, 37)
                            .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(mostrartodoscatbtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtidmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtidpromocion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eliminarcatbtn)
                    .addComponent(añadircatbtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modificarcatbtn)
                    .addComponent(buscarcatbtn))
                .addGap(18, 18, 18)
                .addComponent(mostrartodoscatbtn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void añadircatbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadircatbtnActionPerformed
       CategoriaControlador catc=new CategoriaControlador();
       catc.registrarcategoria(txtid.getText(), txtdescripcion.getText(), txtidmenu.getText(), txtidpromocion.getText());
    }//GEN-LAST:event_añadircatbtnActionPerformed

    private void eliminarcatbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarcatbtnActionPerformed
        CategoriaControlador catc=new CategoriaControlador();
        catc.eliminarcategoria(txtid.getText());
    }//GEN-LAST:event_eliminarcatbtnActionPerformed

    private void modificarcatbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarcatbtnActionPerformed
        CategoriaControlador catc=new CategoriaControlador();
        catc.modificarCategoria(txtid.getText(), txtdescripcion.getText());
    }//GEN-LAST:event_modificarcatbtnActionPerformed

    private void buscarcatbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarcatbtnActionPerformed
        CategoriaControlador catc=new CategoriaControlador();
        txtdescripcion.setText(catc.buscarcategoria(txtid.getText()).getTipodeproducto());
        txtidmenu.setText(catc.buscarcategoria(txtid.getText()).getIdmenu()+"");
        txtidpromocion.setText(catc.buscarcategoria(txtid.getText()).getIdpromocion()+"");
    }//GEN-LAST:event_buscarcatbtnActionPerformed

    private void mostrartodoscatbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrartodoscatbtnActionPerformed
      CategoriaControlador catc=new CategoriaControlador();
      t=new DefaultTableModel();
      tabla3.setModel(t);
      t.addColumn("Id Categoria");
      t.addColumn("tipo de producto");
      t.addColumn("id menu");
      t.addColumn("id promocion");
      
        for (int i = 0; i < catc.mostrartodos().size(); i++) {
            Object fila[]=new Object[4];
            
            fila[0]=catc.mostrartodos().get(i).getId();
            fila[1]=catc.mostrartodos().get(i).getTipodeproducto();
            fila[2]=catc.mostrartodos().get(i).getIdmenu();
            fila[3]=catc.mostrartodos().get(i).getIdpromocion();
            t.addRow(fila);
        }
    }//GEN-LAST:event_mostrartodoscatbtnActionPerformed

    DefaultTableModel t;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton añadircatbtn;
    private javax.swing.JButton buscarcatbtn;
    private javax.swing.JButton eliminarcatbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modificarcatbtn;
    private javax.swing.JButton mostrartodoscatbtn;
    private javax.swing.JTable tabla3;
    private javax.swing.JTextField txtdescripcion;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtidmenu;
    private javax.swing.JTextField txtidpromocion;
    // End of variables declaration//GEN-END:variables
}
