/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controlador.MonederoControlador;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author esteb
 */
public class VentanaMonedero extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaMonedero
     */
    public VentanaMonedero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtrut = new javax.swing.JTextField();
        txtsaldo = new javax.swing.JTextField();
        añadirbtn = new javax.swing.JButton();
        buscarbtn = new javax.swing.JButton();
        mostrartodosbtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        mitabla6 = new javax.swing.JTable();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gestionar Monedero");

        jLabel1.setText("Rut ");

        jLabel2.setText("Saldo ");

        añadirbtn.setBackground(new java.awt.Color(255, 0, 0));
        añadirbtn.setForeground(new java.awt.Color(255, 255, 255));
        añadirbtn.setText("Añadir Saldo");
        añadirbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirbtnActionPerformed(evt);
            }
        });

        buscarbtn.setBackground(new java.awt.Color(255, 0, 0));
        buscarbtn.setForeground(new java.awt.Color(255, 255, 255));
        buscarbtn.setText("Buscar Alumno");
        buscarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarbtnActionPerformed(evt);
            }
        });

        mostrartodosbtn.setBackground(new java.awt.Color(255, 0, 0));
        mostrartodosbtn.setForeground(new java.awt.Color(255, 255, 255));
        mostrartodosbtn.setText("Mostrar todos los alumnos");
        mostrartodosbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrartodosbtnActionPerformed(evt);
            }
        });

        mitabla6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(mitabla6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(añadirbtn)
                        .addGap(40, 40, 40)
                        .addComponent(buscarbtn)
                        .addGap(87, 87, 87))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(44, 44, 44)
                                .addComponent(txtrut, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(35, 35, 35)
                                .addComponent(txtsaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(119, 119, 119))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(mostrartodosbtn)
                        .addGap(133, 133, 133))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtrut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtsaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(añadirbtn)
                    .addComponent(buscarbtn))
                .addGap(35, 35, 35)
                .addComponent(mostrartodosbtn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void añadirbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirbtnActionPerformed
     MonederoControlador monc=new MonederoControlador();
     monc.añadirsaldo(txtrut.getText(), txtsaldo.getText());
    }//GEN-LAST:event_añadirbtnActionPerformed

    private void buscarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarbtnActionPerformed
       MonederoControlador monc=new MonederoControlador();
       txtsaldo.setText(monc.buscar(txtrut.getText()).getSaldo()+"");
    }//GEN-LAST:event_buscarbtnActionPerformed

    private void mostrartodosbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrartodosbtnActionPerformed
        MonederoControlador monc=new MonederoControlador();
        t=new DefaultTableModel();
        mitabla6.setModel(t);
        
        t.addColumn("Rut");
        t.addColumn("Saldo");
        
        for (int i = 0; i < monc.mostartodos().size(); i++) {
            
            Object fila[]=new Object[3];
            
            fila[0]=monc.mostartodos().get(i).getRut();
            fila[1]=monc.mostartodos().get(i).getSaldo();
            t.addRow(fila);
        }
    }//GEN-LAST:event_mostrartodosbtnActionPerformed

    DefaultTableModel t;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton añadirbtn;
    private javax.swing.JButton buscarbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTable mitabla6;
    private javax.swing.JButton mostrartodosbtn;
    private javax.swing.JTextField txtrut;
    private javax.swing.JTextField txtsaldo;
    // End of variables declaration//GEN-END:variables
}
