/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controlador.MenuControlador;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author esteb
 */
public class VentanaMenu extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaMenu
     */
    public VentanaMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtdescripcion = new javax.swing.JTextField();
        txtvalor = new javax.swing.JTextField();
        añadirbtn = new javax.swing.JButton();
        eliminarbtn = new javax.swing.JButton();
        modificarbtn = new javax.swing.JButton();
        buscarmnu = new javax.swing.JButton();
        mostrartodos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla4 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gestionar Menu");

        jLabel1.setText("id Menu ");

        jLabel2.setText("Descripcion");

        jLabel3.setText("Valor ");

        añadirbtn.setBackground(new java.awt.Color(255, 0, 0));
        añadirbtn.setForeground(new java.awt.Color(255, 255, 255));
        añadirbtn.setText("Añadir menu");
        añadirbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirbtnActionPerformed(evt);
            }
        });

        eliminarbtn.setBackground(new java.awt.Color(255, 0, 0));
        eliminarbtn.setForeground(new java.awt.Color(255, 255, 255));
        eliminarbtn.setText("Eliminar menu");
        eliminarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarbtnActionPerformed(evt);
            }
        });

        modificarbtn.setBackground(new java.awt.Color(255, 0, 0));
        modificarbtn.setForeground(new java.awt.Color(255, 255, 255));
        modificarbtn.setText("Modificar menu");
        modificarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarbtnActionPerformed(evt);
            }
        });

        buscarmnu.setBackground(new java.awt.Color(255, 0, 0));
        buscarmnu.setForeground(new java.awt.Color(255, 255, 255));
        buscarmnu.setText("Buscar menu");
        buscarmnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarmnuActionPerformed(evt);
            }
        });

        mostrartodos.setBackground(new java.awt.Color(255, 0, 0));
        mostrartodos.setForeground(new java.awt.Color(255, 255, 255));
        mostrartodos.setText("Mostrar todos");
        mostrartodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrartodosActionPerformed(evt);
            }
        });

        tabla4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtid)
                            .addComponent(txtdescripcion)
                            .addComponent(txtvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(100, 100, 100)
                            .addComponent(buscarmnu)
                            .addGap(56, 56, 56)
                            .addComponent(mostrartodos)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(añadirbtn)
                            .addGap(49, 49, 49)
                            .addComponent(eliminarbtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(modificarbtn))))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addComponent(txtdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtvalor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(añadirbtn)
                    .addComponent(eliminarbtn)
                    .addComponent(modificarbtn))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarmnu)
                    .addComponent(mostrartodos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void añadirbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirbtnActionPerformed
       MenuControlador mc=new MenuControlador();
       mc.añadir(txtid.getText(), txtdescripcion.getText(), txtvalor.getText());
    }//GEN-LAST:event_añadirbtnActionPerformed

    private void eliminarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarbtnActionPerformed
       MenuControlador mc=new MenuControlador();
       mc.eliminar(txtid.getText());
    }//GEN-LAST:event_eliminarbtnActionPerformed

    private void modificarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarbtnActionPerformed
       MenuControlador mc=new MenuControlador();
       mc.modificar(txtid.getText(), txtdescripcion.getText(), txtvalor.getText());
    }//GEN-LAST:event_modificarbtnActionPerformed

    private void buscarmnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarmnuActionPerformed
       MenuControlador mc=new MenuControlador();
       txtdescripcion.setText(mc.buscar(txtid.getText()).getDescripcion());
       txtvalor.setText(mc.buscar(txtid.getText()).getValor()+"");
    }//GEN-LAST:event_buscarmnuActionPerformed

    private void mostrartodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrartodosActionPerformed
        MenuControlador mc=new MenuControlador();
        t=new DefaultTableModel();
        tabla4.setModel(t);
        
        t.addColumn("id");
        t.addColumn("descripcion");
        t.addColumn("valor");
        for (int i = 0; i < mc.mostrartodos().size(); i++) {
          Object fila[]=new Object[4];
          
          fila[0]=mc.mostrartodos().get(i).getId();
          fila[1]=mc.mostrartodos().get(i).getDescripcion();
          fila[2]=mc.mostrartodos().get(i).getValor();
          t.addRow(fila);
        }
        
         
        
    }//GEN-LAST:event_mostrartodosActionPerformed

    DefaultTableModel t;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton añadirbtn;
    private javax.swing.JButton buscarmnu;
    private javax.swing.JButton eliminarbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modificarbtn;
    private javax.swing.JButton mostrartodos;
    private javax.swing.JTable tabla4;
    private javax.swing.JTextField txtdescripcion;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtvalor;
    // End of variables declaration//GEN-END:variables
}
